version: "3.8"

networks:
  bridge:
    driver: bridge

services:
  mysql:
    image: mysql:8.0.33
    restart: always
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: TestTaskManager
      TZ: America/Sao_Paulo
    ports:
      - "3306:3306"
    networks:
      - bridge
  taskmanager:
    image: taskmanager
    restart: always
    depends_on:
      - mysql
    environment:
      TZ: America/Sao_Paulo
      ConnectionStrings__TaskManager: "Server=mysql;Port=3306;Database=taskmanagerdb;Uid=root;Pwd=TestTaskManager;SslMode=Required;"
    container_name: container-taskmanager
    ports:
      - "5011:8080"
    networks:
      - bridge
