version: "3.8"

networks:
  bridge:
    driver: bridge

services:
  taskmanager:
    image: taskmanager
    restart: always
    environment:
      TZ: America/Sao_Paulo
    container_name: container-taskmanager
    ports:
      - "5011:80"
    networks:
      - bridge